#!/usr/bin/env python3
"""Train CT+Text student with cached teacher logits only.

This is a standalone 0534 optimization entrypoint.  It does not modify or call
the online-teacher KD loop; teacher information is read from a CSV generated by
cache_teacher_soft_targets.py.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F
from torch import nn
from torch.utils.data import DataLoader, Dataset

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
for path in (SRC_ROOT, PROJECT_ROOT):
    s = str(path)
    if s not in sys.path:
        sys.path.insert(0, s)

from lung_cancer_cls.multimodal_teacher_student import (  # noqa: E402
    MultiModalTrainConfig,
    apply_text_feature_safety_after_split,
    build_epoch_log,
    build_multimodal_cohort,
    create_model_from_config,
    evaluate_model,
    filter_cohort_to_manifest,
    load_split_manifest_indices,
    move_inputs_to_device,
    normalize_modalities,
    predict_probabilities,
    prepare_dataloaders,
    save_prediction_csv,
    save_split_manifest,
    set_seed,
    split_cohort,
    validate_patient_split_integrity,
)
from lung_cancer_cls.train import resolve_selection_metric, resolve_selection_score  # noqa: E402
from lung_cancer_cls.training_components import build_class_weights, create_loss, create_optimizer, create_scheduler  # noqa: E402


class SampleIdDataset(Dataset):
    def __init__(self, base: Dataset):
        self.base = base
        self.sample_ids = getattr(base, "sample_ids")

    def __len__(self) -> int:
        return len(self.base)

    def __getitem__(self, idx: int):
        inputs, label = self.base[idx]
        return inputs, label, self.sample_ids[idx]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cached-teacher-targets", type=Path, required=True)
    p.add_argument("--reference-teacher-targets", type=Path, default=None)
    p.add_argument("--s0-predictions", type=Path, default=None, help="Optional CT+Text supervised baseline predictions CSV for advantage_learnable weighting.")
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--data-root", type=Path, required=True)
    p.add_argument("--metadata-csv", type=Path, required=True)
    p.add_argument("--reference-manifest", type=Path, required=True)
    p.add_argument("--ct-root", type=Path, default=None)
    p.add_argument("--text-feature-tsv", type=Path, default=None)
    p.add_argument("--text-health-csv", type=Path, default=None)
    p.add_argument("--text-disease-csv", type=Path, default=None)
    p.add_argument("--text-cache-tsv", type=Path, default=None)
    p.add_argument("--label-col", type=str, default="样本类型")
    p.add_argument("--metadata-sample-id-col", type=str, default="SampleID")
    p.add_argument("--patient-id-col", type=str, default=None)
    p.add_argument("--metadata-text-id-col", type=str, default="record_id")
    p.add_argument("--split-col", type=str, default="CT_train_val_split")
    p.add_argument("--ct-path-col", type=str, default="CT_numpy_cloud路径")
    p.add_argument("--text-record-id-col", type=str, default="record_id")
    p.add_argument("--class-mode", type=str, choices=["multiclass", "binary"], default="binary")
    p.add_argument("--binary-task", type=str, default="malignant_vs_normal")
    p.add_argument("--modalities", type=str, default="ct,text")
    p.add_argument("--split-mode", type=str, default="train_val_test")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--cpu", action="store_true")
    p.add_argument("--ct-model", type=str, default="densenet3d_121")
    p.add_argument("--pretrained", action="store_true")
    p.add_argument("--disable-3d-input", action="store_true")
    p.add_argument("--depth-size", type=int, default=128)
    p.add_argument("--volume-hw", type=int, default=256)
    p.add_argument("--image-size", type=int, default=224)
    p.add_argument("--aug-profile", type=str, choices=["basic", "strong"], default="strong")
    p.add_argument("--ct-feature-dim", type=int, default=128)
    p.add_argument("--text-feature-dim", type=int, default=256)
    p.add_argument("--gene-hidden-dim", type=int, default=256)
    p.add_argument("--fusion-hidden-dim", type=int, default=256)
    p.add_argument("--dropout", type=float, default=0.3)
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--grad-accum-steps", type=int, default=1)
    p.add_argument("--num-workers", type=int, default=2)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--optimizer", type=str, choices=["adamw", "sgd"], default="adamw")
    p.add_argument("--scheduler", type=str, choices=["none", "cosine", "warmup_cosine", "onecycle", "plateau"], default="cosine")
    p.add_argument("--warmup-epochs", type=int, default=3)
    p.add_argument("--loss", type=str, choices=["ce", "focal"], default="ce")
    p.add_argument("--label-smoothing", type=float, default=0.05)
    p.add_argument("--focal-gamma", type=float, default=2.0)
    p.add_argument("--sampling-strategy", type=str, choices=["default", "weighted"], default="weighted")
    p.add_argument("--class-weight-strategy", type=str, choices=["none", "inverse", "sqrt_inverse", "effective_num"], default="effective_num")
    p.add_argument("--effective-num-beta", type=float, default=0.999)
    p.add_argument("--distillation-alpha", type=float, default=0.1)
    p.add_argument("--distillation-temperature", type=float, default=4.0)
    p.add_argument("--selection-metric", type=str, choices=["auto", "accuracy", "balanced_accuracy", "auroc", "auprc", "f1", "loss"], default="auroc")
    p.add_argument("--composite-selection-metric", action="store_true")
    p.add_argument("--strict-no-leakage", action="store_true")
    p.add_argument("--disable-text-numeric-features", action="store_true")
    p.add_argument("--allowed-text-cols", type=str, default=None)
    p.add_argument("--allowed-numeric-cols", type=str, default=None)
    p.add_argument("--forbidden-feature-keywords", type=str, default=None)
    p.add_argument("--amp", action="store_true")
    p.add_argument("--ema", type=float, default=0.0, help="EMA decay; 0 disables EMA.")
    p.add_argument("--gradient-clip", type=float, default=0.0)
    p.add_argument("--early-stopping-patience", type=int, default=0)
    p.add_argument("--kd-weighting", type=str, choices=["none", "confidence", "margin", "advantage", "advantage_learnable"], default="none")
    p.add_argument("--kd-weight-floor", type=float, default=0.0)
    p.add_argument("--kd-weight-max", type=float, default=1.0)
    p.add_argument("--no-save-predictions", action="store_true")
    return p.parse_args()


def make_config(args: argparse.Namespace) -> MultiModalTrainConfig:
    return MultiModalTrainConfig(
        data_root=args.data_root,
        metadata_csv=args.metadata_csv,
        output_dir=args.output_dir,
        modalities=normalize_modalities(args.modalities),
        reference_manifest=args.reference_manifest,
        ct_root=args.ct_root,
        text_feature_tsv=args.text_feature_tsv,
        text_health_csv=args.text_health_csv,
        text_disease_csv=args.text_disease_csv,
        text_cache_tsv=args.text_cache_tsv,
        label_col=args.label_col,
        metadata_sample_id_col=args.metadata_sample_id_col,
        patient_id_col=args.patient_id_col,
        metadata_text_id_col=args.metadata_text_id_col,
        split_col=args.split_col,
        ct_path_col=args.ct_path_col,
        text_record_id_col=args.text_record_id_col,
        strict_no_leakage=args.strict_no_leakage,
        disable_text_numeric_features=args.disable_text_numeric_features,
        allowed_text_cols=args.allowed_text_cols,
        allowed_numeric_cols=args.allowed_numeric_cols,
        forbidden_feature_keywords=args.forbidden_feature_keywords,
        class_mode=args.class_mode,
        binary_task=args.binary_task,
        selection_metric=args.selection_metric,
        split_mode=args.split_mode,
        seed=args.seed,
        cpu=args.cpu,
        ct_model=args.ct_model,
        pretrained=args.pretrained,
        use_3d_input=not args.disable_3d_input,
        depth_size=args.depth_size,
        volume_hw=args.volume_hw,
        image_size=args.image_size,
        aug_profile=args.aug_profile,
        ct_feature_dim=args.ct_feature_dim,
        text_feature_dim=args.text_feature_dim,
        gene_hidden_dim=args.gene_hidden_dim,
        fusion_hidden_dim=args.fusion_hidden_dim,
        dropout=args.dropout,
        epochs=args.epochs,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        lr=args.lr,
        weight_decay=args.weight_decay,
        optimizer_name=args.optimizer,
        scheduler_name="cosine" if args.scheduler == "warmup_cosine" else args.scheduler,
        loss_name=args.loss,
        label_smoothing=args.label_smoothing,
        focal_gamma=args.focal_gamma,
        sampling_strategy=args.sampling_strategy,
        class_weight_strategy=args.class_weight_strategy,
        effective_num_beta=args.effective_num_beta,
        save_predictions=not args.no_save_predictions,
    )


def load_targets(path: Path) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
        logit_cols = sorted(
            [c for c in fields if c.startswith("teacher_logit_") and c.rsplit("_", 1)[1].isdigit()],
            key=lambda c: int(c.rsplit("_", 1)[1]),
        )
        prob_cols = sorted(
            [c for c in fields if c.startswith("teacher_prob_") and c.rsplit("_", 1)[1].isdigit()],
            key=lambda c: int(c.rsplit("_", 1)[1]),
        )
        for row in reader:
            sid = str(row.get("sample_id", "")).strip()
            if not sid:
                continue
            values = {
                "confidence": float(row.get("teacher_confidence", 0.0)),
                "margin": float(row.get("teacher_margin", 0.0)),
            }
            for col in logit_cols:
                idx = int(col.rsplit("_", 1)[1])
                values[f"logit_{idx}"] = float(row.get(col, 0.0))
            for col in prob_cols:
                idx = int(col.rsplit("_", 1)[1])
                values[f"prob_{idx}"] = float(row.get(col, 0.0))
            if values["confidence"] <= 0.0 and prob_cols:
                values["confidence"] = max(values[f"prob_{int(col.rsplit('_', 1)[1])}"] for col in prob_cols)
            out[sid] = values
    if not out:
        raise RuntimeError(f"No cached teacher targets loaded: {path}")
    return out


def _float_or_none(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def load_prediction_probs(path: Path | None) -> dict[str, dict[str, float]]:
    if path is None:
        return {}
    out: dict[str, dict[str, float]] = {}
    if not path.is_file():
        return out
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
        id_col = "sample_id" if "sample_id" in fields else ("record_id" if "record_id" in fields else None)
        if id_col is None:
            return out
        for row in reader:
            sid = str(row.get(id_col, "")).strip()
            if not sid:
                continue
            probs: dict[int, float] = {}
            for col in fields:
                if col.startswith("prob_") and col[5:].isdigit():
                    value = _float_or_none(row.get(col))
                    if value is not None:
                        probs[int(col[5:])] = value
            malignant_idx = 2 if "prob_benign" in fields else 1
            for name, idx in {"normal": 0, "benign": 1, "malignant": malignant_idx, "non_malignant": 0}.items():
                col = f"prob_{name}"
                if col in row:
                    value = _float_or_none(row.get(col))
                    if value is not None:
                        probs[idx] = value
            if probs:
                out[sid] = {f"prob_{idx}": max(0.0, min(1.0, float(value))) for idx, value in probs.items()}
                continue
            p1 = None
            for col in ("prob_1", "prob_malignant", "prob_pos", "y_prob", "score", "probability_malignant", "p"):
                if col in row:
                    p1 = _float_or_none(row.get(col))
                    if p1 is not None:
                        break
            p0 = None
            for col in ("prob_0", "prob_normal", "prob_negative"):
                if col in row:
                    p0 = _float_or_none(row.get(col))
                    if p0 is not None:
                        break
            if p1 is None and p0 is None:
                continue
            if p1 is None and p0 is not None:
                p1 = 1.0 - p0
            if p0 is None and p1 is not None:
                p0 = 1.0 - p1
            out[sid] = {
                "prob_0": max(0.0, min(1.0, float(p0))),
                "prob_1": max(0.0, min(1.0, float(p1))),
            }
    return out


def true_prob(values: dict[str, float], label: int) -> float:
    return float(values.get(f"prob_{int(label)}", 0.0))


def class_indices(values: dict[str, float], prefix: str = "logit_") -> list[int]:
    indices: list[int] = []
    for key in values:
        if key.startswith(prefix):
            suffix = key[len(prefix):]
            if suffix.isdigit():
                indices.append(int(suffix))
    return sorted(indices)


def raw_kd_weight(
    sid: str,
    label: int,
    targets: dict[str, dict[str, float]],
    ref_targets: dict[str, dict[str, float]] | None,
    s0_predictions: dict[str, dict[str, float]],
    weighting: str,
) -> tuple[float, dict[str, float]]:
    t1 = targets[sid]
    if weighting == "confidence":
        return float(t1["confidence"]), {}
    if weighting == "margin":
        return float(t1["margin"]), {}
    if weighting == "advantage":
        if ref_targets is None or sid not in ref_targets:
            return 0.0, {"gene_advantage": 0.0}
        gene_advantage = max(0.0, true_prob(t1, label) - true_prob(ref_targets[sid], label))
        return gene_advantage, {"gene_advantage": gene_advantage}
    if weighting != "advantage_learnable":
        return 1.0, {}
    if ref_targets is None or sid not in ref_targets:
        return 0.0, {
            "gene_advantage": 0.0,
            "teacher_confidence": true_prob(t1, label),
            "ct_text_support": 0.0,
            "confidence_penalty": 0.0,
        }

    t0 = ref_targets[sid]
    p_t1_true = true_prob(t1, label)
    p_t0_true = true_prob(t0, label)
    support_source = s0_predictions.get(sid, t0)
    p_support_true = true_prob(support_source, label)
    gene_advantage = max(0.0, p_t1_true - p_t0_true)
    teacher_confidence = p_t1_true
    ct_text_support = max(0.0, min(1.0, 1.0 - abs(p_support_true - 0.5) * 2.0))
    confidence_penalty = min(1.0, max(0.0, p_t0_true / 0.2), max(0.0, p_support_true / 0.2))
    raw = gene_advantage * teacher_confidence * ct_text_support * confidence_penalty
    return raw, {
        "gene_advantage": gene_advantage,
        "teacher_confidence": teacher_confidence,
        "ct_text_support": ct_text_support,
        "confidence_penalty": confidence_penalty,
        "p_t1_true": p_t1_true,
        "p_t0_true": p_t0_true,
        "p_support_true": p_support_true,
    }


def prepare_kd_weight_lookup(
    sample_ids: list[str],
    labels: list[int],
    targets: dict[str, dict[str, float]],
    ref_targets: dict[str, dict[str, float]] | None,
    s0_predictions: dict[str, dict[str, float]],
    args: argparse.Namespace,
) -> tuple[dict[str, float], dict[str, Any]]:
    raw_rows: list[dict[str, Any]] = []
    for sid, label in zip(sample_ids, labels):
        if sid not in targets:
            raise KeyError(f"sample_id missing in cached teacher targets: {sid}")
        raw, parts = raw_kd_weight(sid, int(label), targets, ref_targets, s0_predictions, args.kd_weighting)
        raw_rows.append({"sample_id": sid, "label": int(label), "raw_weight": float(raw), **parts})

    max_raw = max((r["raw_weight"] for r in raw_rows), default=0.0)
    weights: dict[str, float] = {}
    for row in raw_rows:
        if args.kd_weighting == "advantage_learnable":
            normalized = row["raw_weight"] / max_raw if max_raw > 0 else 0.0
        else:
            normalized = row["raw_weight"]
        weights[row["sample_id"]] = max(float(args.kd_weight_floor), min(float(args.kd_weight_max), float(normalized)))

    values = list(weights.values())
    mean = float(np.mean(values)) if values else 0.0
    std = float(np.std(values)) if values else 0.0
    top_rows = sorted(raw_rows, key=lambda r: weights.get(r["sample_id"], 0.0), reverse=True)[:20]
    zero_rows = [r for r in raw_rows if weights.get(r["sample_id"], 0.0) <= 0.0]
    summary = {
        "kd_weighting": args.kd_weighting,
        "num_samples": len(values),
        "mean": mean,
        "std": std,
        "min": float(min(values)) if values else 0.0,
        "max": float(max(values)) if values else 0.0,
        "raw_max_before_normalization": float(max_raw),
        "s0_predictions_available": bool(s0_predictions),
        "top_weighted_samples": [
            {**row, "weight": weights.get(row["sample_id"], 0.0)} for row in top_rows
        ],
        "zero_weight_samples": [
            {**row, "weight": weights.get(row["sample_id"], 0.0)} for row in zero_rows[:200]
        ],
        "zero_weight_samples_count": len(zero_rows),
        "T1_advantage_samples_count": sum(1 for row in raw_rows if float(row.get("gene_advantage", 0.0)) > 0.0),
        "learnable_advantage_samples_count": sum(1 for row in raw_rows if row["raw_weight"] > 0.0),
    }
    return weights, summary


def create_scheduler_for_cached(args: argparse.Namespace, optimizer, steps_per_epoch: int):
    if args.scheduler != "warmup_cosine":
        return create_scheduler(args.scheduler, optimizer, args.epochs, steps_per_epoch)
    total_steps = max(1, int(args.epochs) * max(1, steps_per_epoch))
    warmup_steps = max(1, int(args.warmup_epochs) * max(1, steps_per_epoch))

    def lr_lambda(step_idx: int) -> float:
        if step_idx < warmup_steps:
            return (step_idx + 1) / float(warmup_steps)
        progress = (step_idx - warmup_steps) / float(max(1, total_steps - warmup_steps))
        progress = min(max(progress, 0.0), 1.0)
        return 0.5 * (1.0 + math.cos(math.pi * progress))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda), True


def composite_score(metrics: dict[str, Any]) -> tuple[float, str]:
    values = {
        "auroc": metrics.get("auroc"),
        "balanced_accuracy": metrics.get("balanced_accuracy"),
        "f1": metrics.get("f1"),
        "recall": metrics.get("recall"),
        "ece": metrics.get("ece"),
    }
    if any(values[k] is None for k in values):
        score, used = resolve_selection_score(metrics, "auroc")
        return float(score), used
    return (
        float(values["auroc"])
        + 0.5 * float(values["balanced_accuracy"])
        + 0.5 * float(values["f1"])
        + 0.25 * float(values["recall"])
        - 0.25 * float(values["ece"]),
        "composite_auroc_bacc_f1_recall_ece",
    )


def batch_teacher_tensors(
    sample_ids: list[str],
    labels: torch.Tensor,
    targets: dict[str, dict[str, float]],
    ref_targets: dict[str, dict[str, float]] | None,
    kd_weight_lookup: dict[str, float] | None,
    temperature: float,
    weighting: str,
    floor: float,
    max_weight: float,
    device: torch.device,
) -> tuple[torch.Tensor, torch.Tensor]:
    logits = []
    weights = []
    temp = max(float(temperature), 1e-4)
    for sid, label in zip(sample_ids, labels.detach().cpu().tolist()):
        if sid not in targets:
            raise KeyError(f"sample_id missing in cached teacher targets: {sid}")
        t = targets[sid]
        indices = class_indices(t, "logit_")
        if not indices:
            raise KeyError(f"No teacher logits found for sample_id={sid}")
        logits.append([t[f"logit_{idx}"] for idx in indices])
        if kd_weight_lookup is not None:
            w = kd_weight_lookup.get(sid, 0.0)
        elif weighting == "confidence":
            w = t["confidence"]
        elif weighting == "margin":
            w = t["margin"]
        elif weighting == "advantage":
            if ref_targets is None or sid not in ref_targets:
                w = 0.0
            else:
                w = max(0.0, true_prob(t, int(label)) - true_prob(ref_targets[sid], int(label)))
        else:
            w = 1.0
        weights.append(max(float(floor), min(float(max_weight), float(w))))
    teacher_logits = torch.tensor(logits, dtype=torch.float32, device=device)
    teacher_probs = F.softmax(teacher_logits / temp, dim=1)
    return teacher_probs, torch.tensor(weights, dtype=torch.float32, device=device)


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    scaler: torch.cuda.amp.GradScaler | None,
    args: argparse.Namespace,
    targets: dict[str, dict[str, float]],
    ref_targets: dict[str, dict[str, float]] | None,
    kd_weight_lookup: dict[str, float] | None,
    scheduler=None,
    scheduler_step_per_batch: bool = False,
) -> dict[str, float]:
    model.train()
    optimizer.zero_grad(set_to_none=True)
    seen = 0
    total_loss = total_ce = total_kd = 0.0
    accum = max(1, int(args.grad_accum_steps))

    for step, (inputs, labels, sample_ids) in enumerate(loader, start=1):
        inputs = move_inputs_to_device(inputs, device)
        labels = labels.to(device)
        sample_ids = [str(x) for x in sample_ids]
        teacher_probs, weights = batch_teacher_tensors(
            sample_ids,
            labels,
            targets,
            ref_targets,
            kd_weight_lookup,
            args.distillation_temperature,
            args.kd_weighting,
            args.kd_weight_floor,
            args.kd_weight_max,
            device,
        )
        use_amp = bool(args.amp and device.type == "cuda")
        with torch.cuda.amp.autocast(enabled=use_amp):
            logits = model(inputs)
            ce = criterion(logits, labels)
            log_prob = F.log_softmax(logits / max(args.distillation_temperature, 1e-4), dim=1)
            kd_per = F.kl_div(log_prob, teacher_probs, reduction="none", log_target=False).sum(dim=1)
            kd_per = kd_per * (max(args.distillation_temperature, 1e-4) ** 2)
            kd = (kd_per * weights).sum() / weights.sum().clamp_min(1e-12)
            loss = ce + float(args.distillation_alpha) * kd
            scaled_loss = loss / accum

        if scaler is not None:
            scaler.scale(scaled_loss).backward()
        else:
            scaled_loss.backward()

        do_step = step % accum == 0 or step == len(loader)
        if do_step:
            if args.gradient_clip > 0:
                if scaler is not None:
                    scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), float(args.gradient_clip))
            if scaler is not None:
                scaler.step(optimizer)
                scaler.update()
            else:
                optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            if scheduler is not None and scheduler_step_per_batch:
                scheduler.step()

        bs = int(labels.size(0))
        seen += bs
        total_loss += float(loss.detach().item()) * bs
        total_ce += float(ce.detach().item()) * bs
        total_kd += float(kd.detach().item()) * bs

    denom = max(1, seen)
    return {"loss": total_loss / denom, "ce_loss": total_ce / denom, "kd_loss": total_kd / denom}


def ema_update(shadow: dict[str, torch.Tensor], model: nn.Module, decay: float) -> None:
    with torch.no_grad():
        for name, param in model.state_dict().items():
            if not torch.is_floating_point(param):
                shadow[name] = param.detach().clone()
            elif name not in shadow:
                shadow[name] = param.detach().clone()
            else:
                shadow[name].mul_(decay).add_(param.detach(), alpha=1.0 - decay)


def evaluate_with_optional_ema(model, shadow, loader, device, criterion, class_names):
    if not shadow:
        return evaluate_model(model, loader, device, criterion, class_names)
    current = {k: v.detach().clone() for k, v in model.state_dict().items()}
    model.load_state_dict(shadow, strict=True)
    metrics = evaluate_model(model, loader, device, criterion, class_names)
    model.load_state_dict(current, strict=True)
    return metrics


def jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(k): jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [jsonable(v) for v in value]
    return value


def main() -> int:
    args = parse_args()
    if args.kd_weighting in {"advantage", "advantage_learnable"} and args.reference_teacher_targets is None:
        raise ValueError("--reference-teacher-targets is required for --kd-weighting advantage/advantage_learnable")
    if args.grad_accum_steps < 1:
        raise ValueError("--grad-accum-steps must be >= 1")
    if "hint" in str(args).lower():
        raise ValueError("hint distillation is disabled in cached-logits search")

    set_seed(args.seed)
    config = make_config(args)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    targets = load_targets(args.cached_teacher_targets)
    ref_targets = load_targets(args.reference_teacher_targets) if args.reference_teacher_targets else None
    s0_predictions = load_prediction_probs(args.s0_predictions)

    cohort, feature_info, class_names, cohort_stats = build_multimodal_cohort(config, config.modalities)
    cohort = filter_cohort_to_manifest(cohort, config.reference_manifest)
    train_idx, val_idx, test_idx = load_split_manifest_indices(cohort, config.reference_manifest)
    if not train_idx:
        raise RuntimeError("Training split is empty.")
    leakage_warnings = validate_patient_split_integrity(
        cohort,
        train_idx,
        val_idx,
        test_idx,
        "patient_id" if config.patient_id_col else None,
        strict=config.strict_no_leakage,
    )
    cohort, feature_info, text_warnings = apply_text_feature_safety_after_split(
        config, cohort, feature_info, train_idx, val_idx, test_idx
    )
    leakage_warnings.extend(text_warnings)
    save_split_manifest(config.output_dir / "split_manifest.csv", cohort, train_idx, val_idx, test_idx)

    train_ds, val_ds, test_ds, train_loader_base, val_loader, test_loader, train_eval_loader = prepare_dataloaders(
        config, cohort, feature_info, config.modalities, (train_idx, val_idx, test_idx)
    )
    train_loader = DataLoader(
        SampleIdDataset(train_ds),
        batch_size=args.batch_size,
        sampler=train_loader_base.sampler,
        shuffle=False,
        num_workers=args.num_workers,
    )
    train_label_counts = [0 for _ in range(len(class_names))]
    for label in train_ds.labels:
        train_label_counts[int(label)] += 1
    kd_weight_lookup, kd_weight_summary = prepare_kd_weight_lookup(
        list(train_ds.sample_ids),
        list(train_ds.labels),
        targets,
        ref_targets,
        s0_predictions,
        args,
    )
    (config.output_dir / "kd_sample_weights_summary.json").write_text(
        json.dumps(kd_weight_summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    model = create_model_from_config(config, feature_info, class_names).to(device)
    optimizer = create_optimizer(args.optimizer, model.parameters(), args.lr, args.weight_decay)
    criterion = create_loss(
        args.loss,
        label_smoothing=args.label_smoothing,
        focal_gamma=args.focal_gamma,
        class_weights=build_class_weights(
            train_label_counts,
            strategy=args.class_weight_strategy,
            effective_num_beta=args.effective_num_beta,
        ),
    ).to(device)
    scheduler, scheduler_step_per_batch = create_scheduler_for_cached(args, optimizer, len(train_loader))
    scaler = torch.cuda.amp.GradScaler(enabled=bool(args.amp and device.type == "cuda"))
    scaler = scaler if bool(args.amp and device.type == "cuda") else None
    selection_metric = resolve_selection_metric(args.selection_metric, len(class_names))

    best_score = -float("inf")
    best_epoch = 0
    best_val_metrics: dict[str, Any] | None = None
    history: list[dict[str, Any]] = []
    shadow: dict[str, torch.Tensor] = {}
    stale_epochs = 0

    print("=" * 60)
    print("Cached logits KD student training")
    print(f"Cached targets: {args.cached_teacher_targets}")
    print(f"Student modalities: {','.join(config.modalities)}")
    print(f"Output dir: {config.output_dir}")
    print(f"Selection: {'composite' if args.composite_selection_metric else selection_metric}")
    print("=" * 60)

    for epoch in range(1, args.epochs + 1):
        train_stats = train_one_epoch(
            model,
            train_loader,
            device,
            criterion,
            optimizer,
            scaler,
            args,
            targets,
            ref_targets,
            kd_weight_lookup,
            scheduler=scheduler,
            scheduler_step_per_batch=scheduler_step_per_batch,
        )
        if args.ema > 0:
            ema_update(shadow, model, float(args.ema))
        val_metrics = evaluate_with_optional_ema(model, shadow, val_loader, device, criterion, class_names)
        if args.composite_selection_metric:
            score, used_metric = composite_score(val_metrics)
        else:
            score, used_metric = resolve_selection_score(val_metrics, selection_metric)

        if scheduler is not None and not scheduler_step_per_batch:
            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                scheduler.step(score)
            else:
                scheduler.step()

        epoch_log = {
            "epoch": epoch,
            "train_loss": train_stats["loss"],
            "train_ce_loss": train_stats["ce_loss"],
            "train_kd_loss": train_stats["kd_loss"],
            "selection_metric": used_metric,
            "selection_score": float(score),
            "distillation_alpha": args.distillation_alpha,
            "distillation_temperature": args.distillation_temperature,
            "kd_weighting": args.kd_weighting,
            "lr": optimizer.param_groups[0]["lr"],
        }
        epoch_log.update({f"val_{k}": v for k, v in build_epoch_log(val_metrics).items()})
        history.append(epoch_log)

        print(
            f"[Epoch {epoch}/{args.epochs}] train={train_stats['loss']:.4f} "
            f"ce={train_stats['ce_loss']:.4f} kd={train_stats['kd_loss']:.4f} "
            f"val_auc={val_metrics.get('auroc')} val_bacc={val_metrics.get('balanced_accuracy')} "
            f"val_f1={val_metrics.get('f1')} monitor({used_metric})={score:.6f} "
            f"lr={optimizer.param_groups[0]['lr']:.6g}"
        )

        if best_val_metrics is None or score > best_score:
            best_score = float(score)
            best_epoch = epoch
            best_val_metrics = val_metrics
            stale_epochs = 0
            if shadow:
                current = {k: v.detach().clone() for k, v in model.state_dict().items()}
                model.load_state_dict(shadow, strict=True)
                torch.save(model.state_dict(), config.output_dir / "best_model.pt")
                model.load_state_dict(current, strict=True)
            else:
                torch.save(model.state_dict(), config.output_dir / "best_model.pt")
        else:
            stale_epochs += 1
            if args.early_stopping_patience > 0 and stale_epochs >= args.early_stopping_patience:
                print(f"[EARLY_STOP] patience reached at epoch {epoch}")
                break

    model.load_state_dict(torch.load(config.output_dir / "best_model.pt", map_location=device))
    train_metrics = evaluate_model(model, train_eval_loader, device, criterion, class_names)
    val_metrics = evaluate_model(model, val_loader, device, criterion, class_names)
    test_metrics = evaluate_model(model, test_loader, device, criterion, class_names) if test_loader is not None else None

    if config.save_predictions:
        save_prediction_csv(config.output_dir / "train_predictions.csv", train_ds, predict_probabilities(model, train_eval_loader, device), class_names)
        save_prediction_csv(config.output_dir / "val_predictions.csv", val_ds, predict_probabilities(model, val_loader, device), class_names)
        if test_loader is not None and test_ds is not None:
            save_prediction_csv(config.output_dir / "test_predictions.csv", test_ds, predict_probabilities(model, test_loader, device), class_names)

    metrics = {
        "family": "cached_logits_kd_student",
        "best_epoch": best_epoch,
        "selection_metric": "composite" if args.composite_selection_metric else selection_metric,
        "best_val_metrics": best_val_metrics,
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "class_names": class_names,
        "modalities": list(config.modalities),
        "cached_teacher_targets": str(args.cached_teacher_targets),
        "reference_teacher_targets": str(args.reference_teacher_targets) if args.reference_teacher_targets else "",
        "s0_predictions": str(args.s0_predictions) if args.s0_predictions else "",
        "distillation_alpha": args.distillation_alpha,
        "distillation_temperature": args.distillation_temperature,
        "kd_weighting": args.kd_weighting,
        "kd_sample_weights_summary": kd_weight_summary,
        "cohort_stats": {
            **cohort_stats,
            "num_total": int(len(cohort)),
            "num_train": int(len(train_idx)),
            "num_val": int(len(val_idx)),
            "num_test": int(len(test_idx)),
        },
        "history": history,
        "config": jsonable(asdict(config)),
        "cached_kd_config": jsonable(vars(args)),
        "feature_info": {k: v for k, v in feature_info.items() if k not in {"text_meta"}},
        "leakage_warnings": leakage_warnings,
    }
    with (config.output_dir / "metrics.json").open("w", encoding="utf-8") as f:
        json.dump(metrics, f, ensure_ascii=False, indent=2)
    print("=" * 60)
    print("Cached logits KD training complete")
    print(f"Best epoch: {best_epoch}")
    print(f"Best val score: {best_score}")
    if test_metrics:
        print(f"Test AUROC: {test_metrics.get('auroc')}")
    print(f"Outputs saved to: {config.output_dir}")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
